export const APP_NAME = "El React App"
export const LS_ADMIN_ID = "admin_id";
export const LS_ADMIN_NAME = "admin_name";
export const PAGE_FROM = "page_from";
export const ACTIVE_TAB = "active_tab";
export const DEACTIVATED_TAB = "deactivated_tab";
export const PROFILE_PAGE = "profile_tab";
export const AXIOS_ERR_MSG = "An unknown error occured. Please try again."
export const MIN_PASS_COUNT = 6
export const DEFULT_STUDENT_PASS = "admin@123"